---
# setup file for ansible-role-tui

- name: Copy image to ~/.images/
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.copy:
    src: "{{ image_path }}{{ image }}"
    dest: "{{ ansible_user_dir }}/.images/"
    mode: '0755'

- name: Add .profile template
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.template:
    src: ".profile.j2"
    dest: "{{ ansible_user_dir }}/.profile"
    mode: '0755'